<script src="js/jquery-2.2.4.min.js?v=1.3"></script>
<script src="js/waypoints.min.js"></script>
<script src="js/owl.carousel.js"></script> 
<script src="js/material.min.js"></script>
<script src="js/materialize.min.js"></script>
<script src="js/classie.js"></script>
<script src="js/main.js?v=1.3"></script>
<script src="js/script.js"></script>
<script src="js/sc.js?v=3.0"></script>
<script src="ip_js/ip_script.js?v=3.0"></script>
<script src="lightbox/lity.min.js"></script>